#!/usr/bin/env bash
# Usage: catalog-drift-prs.sh FINDINGS_JSON INPUTS_DIR
#
# The catalog-drift workflow's PR step. For each successor or retirement finding of
# `rates-sync catalog-drift` (FINDINGS_JSON, from the inputs saved in INPUTS_DIR):
#
# 1. On a fresh copy of main: apply its edit (`catalog-apply`), regenerate the rate table and
#    RATE_VERSION, format, and commit it as the bot.
# 2. If `catalog/<slug>` already holds exactly that tree on top of main, stop: nothing changed.
#    If it has anyone else's commit, comment and stop.
# 3. Live test the edited row through a gateway built from that commit: `catalog_live.rs`'s
#    CAT-1 (it serves a real request), BIL-13 (one priced `ai.usage` row at the row) and CAT-7
#    (the logged tokens at the card match what the vendor reports), filtered to the row
#    (`VERIFY_CATALOG_ROW`). Every candidate's provider key must be set; a missing key or a
#    failure makes the finding needs-human, and no PR is opened (an open one loses auto-merge).
# 4. Force-push the branch (with lease), open or update its PR with the live result, dispatch CI
#    on it, and enable squash auto-merge.
#
# Writes $RUNNER_TEMP/demoted.json: [{slug, reason}] for findings the live step made needs-human.
set -euo pipefail
findings=$1
inputs=$2
bot="41898282+github-actions[bot]@users.noreply.github.com"
remote="https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git config user.name "github-actions[bot]"
git config user.email "$bot"
git fetch -q "$remote" "+refs/heads/main:refs/remotes/origin/main"
paths=(crates/providers/src/catalog.rs crates/providers/src/rates.rs
  crates/providers/src/rates/generated.rs verify/catalog_truth.toml verify/pricing_vectors.json
  verify/rates_sources)
demoted="$RUNNER_TEMP/demoted.json"
echo '[]' >"$demoted"
gh label create catalog-auto --force --color 0e8a16 \
  --description "Catalog drift a rule settled and a live test passed: merges itself once CI is green"

demote() {
  local slug=$1 reason=$2 pr=${3:-}
  jq --arg s "$slug" --arg r "$reason" '. + [{slug: $s, reason: $r}]' "$demoted" >"$demoted.tmp"
  mv "$demoted.tmp" "$demoted"
  echo "::warning::$slug needs a human: $reason"
  if [ -n "$pr" ]; then
    gh pr merge "$pr" --disable-auto || true
    gh pr edit "$pr" --remove-label catalog-auto || true
    gh pr comment "$pr" --body "The catalog-drift run $run_url found this needs a human: $reason"
  fi
}

key_var() {
  case "$1" in
    anthropic) echo ANTHROPIC_API_KEY ;;
    openai) echo OPENAI_API_KEY ;;
    openrouter) echo OPENROUTER_API_KEY ;;
    xai) echo XAI_API_KEY ;;
    together) echo TOGETHER_API_KEY ;;
    bedrock) echo AWS_BEARER_TOKEN_BEDROCK ;;
    *) echo "" ;;
  esac
}

run_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
mapfile -t slugs < <(jq -r '.findings[] | select(.class == "successor" or .class == "retirement") | .slug' "$findings")
for slug in "${slugs[@]}"; do
  f=$(jq -c --arg s "$slug" '.findings[] | select(.slug == $s)' "$findings")
  title=$(jq -r .title <<<"$f")
  class=$(jq -r .class <<<"$f")
  branch="catalog/$slug"
  echo "::group::$slug ($class)"
  git reset -q --hard
  git clean -fdq -- verify/rates_sources
  git checkout -q -B "$branch" origin/main
  row=$(cargo run -q -p beyond-ai-rates-sync -- catalog-apply --inputs "$inputs" "$slug" </dev/null)
  cargo run -q -p beyond-ai-rates-sync -- generate </dev/null >/dev/null
  cargo run -q -p beyond-ai-rates-sync -- rate-version </dev/null
  cargo fmt -p beyond-ai-providers
  git add -A -- "${paths[@]}"
  git commit -q -m "$title" -m "Generated by the catalog-drift workflow (rates-sync catalog-drift: $class)."

  pr=$(gh pr list --state open --head "$branch" --json number --jq '.[0].number // empty')
  lease=""
  if git fetch -q "$remote" "+refs/heads/$branch:refs/remotes/origin/$branch" 2>/dev/null; then
    lease=$(git rev-parse "origin/$branch")
    if git diff --quiet "origin/$branch" HEAD && git merge-base --is-ancestor origin/main "origin/$branch"; then
      echo "$branch already carries exactly this change on top of main: nothing to do."
      echo "::endgroup::"
      continue
    fi
    if git log --format='%ae%n%ce' "origin/main..origin/$branch" | grep -qvxF "$bot"; then
      [ -n "$pr" ] && gh pr comment "$pr" --body "The catalog-drift run $run_url would update this branch, but it has a commit from a human, so the workflow did not push. Its finding now:

$(jq -r .markdown <<<"$f")"
      echo "::endgroup::"
      continue
    fi
  fi

  # The live test: every candidate's provider must be one the live suite reaches with a key.
  missing=""
  for p in $(jq -r '.providers[]' <<<"$f"); do
    var=$(key_var "$p")
    if [ -z "$var" ]; then
      missing="$missing $p (no live test reaches it)"
    elif [ -z "${!var:-}" ]; then
      missing="$missing $p ($var is not set)"
    fi
  done
  if [ -n "$missing" ]; then
    demote "$slug" "live test skipped:$missing" "$pr"
    echo "::endgroup::"
    continue
  fi
  cargo build -q -p beyond-ai
  log="$RUNNER_TEMP/live-$slug.log"
  set +e
  # The job sets CARGO_TERM_COLOR=always; the result is parsed below, so no color codes.
  CARGO_TERM_COLOR=never VERIFY_LIVE=1 VERIFY_CATALOG_ROW="$row" cargo nextest run --color never \
    -p beyond-ai-verify --test catalog_live --profile verify --no-fail-fast \
    -E 'test(/^(CAT-1|BIL-13|CAT-7)::/)' >"$log" 2>&1 </dev/null
  code=$?
  set -e
  sed -i 's/\x1b\[[0-9;]*m//g' "$log"
  results=$(grep -E '^ +(PASS|FAIL|SIGSEGV|TIMEOUT|SLOW|LEAK)|^ +Summary|INCONCLUSIVE' "$log" | sed 's/^ *//' || true)
  if [ "$code" != 0 ] || ! grep -q ' passed' <<<"$results"; then
    tail -40 "$log"
    demote "$slug" "live test failed (CAT-1, BIL-13, CAT-7 on $row): $(grep -E '^ +Summary' "$log" | sed 's/^ *//' || echo "exit $code")" "$pr"
    echo "::endgroup::"
    continue
  fi

  body="$RUNNER_TEMP/body-$slug.md"
  {
    jq -r .markdown <<<"$f"
    echo
    echo "### Live test"
    echo
    echo "\`VERIFY_LIVE=1 VERIFY_CATALOG_ROW=$row cargo nextest run -p beyond-ai-verify --test catalog_live --profile verify -E 'test(/^(CAT-1|BIL-13|CAT-7)::/)'\`, through a gateway built from this commit: the row served real requests, logged one priced \`ai.usage\` row each, and the logged tokens at the card match what the vendor reports."
    echo
    echo '```'
    echo "$results"
    echo '```'
    echo
    echo "Generated by the catalog-drift workflow ($run_url), from \`rates-sync catalog-drift\`: deterministic rules, no model in the loop. A rule settled it and the live test passed, so it merges itself (squash) once \`Check\` is green."
  } >"$body"
  if [ -n "$lease" ]; then
    git push -q --force-with-lease="refs/heads/$branch:$lease" "$remote" "HEAD:refs/heads/$branch"
  else
    git push -q "$remote" "HEAD:refs/heads/$branch"
  fi
  if [ -z "$pr" ]; then
    pr=$(gh pr create --base main --head "$branch" --title "$title" --body-file "$body" --label catalog-auto)
  else
    gh pr edit "$pr" --title "$title" --body-file "$body" --add-label catalog-auto
  fi
  gh workflow run ci.yml --ref "$branch"
  gh pr merge "$pr" --auto --squash --delete-branch
  echo "PR: $pr (CI dispatched on $branch)"
  echo "::endgroup::"
done
git reset -q --hard
git clean -fdq -- verify/rates_sources
git checkout -q --detach origin/main
