"""Generate `src/tools/fence_tables.rs`, the angle-bracket lookalike table for `mcp_wire::fence_safe`.

    python3 crates/agent/scripts/gen_angle_lookalikes.py > crates/agent/src/tools/fence_tables.rs

Every character (outside ASCII) whose Unicode name says it *is* a bare angle — an angle bracket or
angle quotation mark (any weight, ornament or presentation form), a chevron or arrowhead pointing
left/right, PRECEDES/SUCCEEDS, or (MUCH/VERY MUCH) LESS-/GREATER-THAN on its own — but not a compound
relation (≤, ≮, ⪕, …), which reads as a different symbol and is not a fence character's shape.
Orientation from the name: LEFT/LESS/PRECEDES → '‹', RIGHT/GREATER/SUCCEEDS → '›'.
"""
import unicodedata

ANGLE = ["ANGLE BRACKET", "ANGLE QUOTATION", "ANGLE BRACKET ORNAMENT", "ANGLE QUOTATION MARK ORNAMENT",
         "ARROWHEAD", "CHEVRON", "PRECEDES", "SUCCEEDS", "LESS-THAN", "GREATER-THAN",
         "POINTING ANGLE"]
COMPOUND = ["EQUAL", "EQUIVALENT", "APPROXIMATE", "SIMILAR", " OR ", "NOT ", "NEITHER", " NOR ",
            "WITH ", "ABOVE", "BELOW", "UNDER", "OVER", " BUT ", " AND ", "THROUGH", " ARC ",
            "QUAD", "CIRCLED", "DOT", "ARROW ", "ARROWS", "TAIL", "BAR", "CLOSED", "RELATION",
            "COMBINING", "SNOWFLAKE", "UP-POINTING", "DOWN-POINTING", "UPWARDS", "DOWNWARDS",
            "SQUARED", "BLACK", "WHITE UP", "WHITE DOWN", "STROKE", "DOUBLE ANGLE QUOTATION"]
LEFT = ["LEFT", "LESS-THAN", "PRECEDES"]
RIGHT = ["RIGHT", "GREATER-THAN", "SUCCEEDS"]

rows = []
for cp in range(0x80, 0x110000):
    c = chr(cp)
    name = unicodedata.name(c, "")
    if not name or not any(a in name for a in ANGLE):
        continue
    if any(x in name for x in COMPOUND):
        continue
    left = any(w in name for w in LEFT)
    right = any(w in name for w in RIGHT)
    if left == right:
        continue
    rows.append((cp, "‹" if left else "›", name))

print(f"//! Generated by `crates/agent/scripts/gen_angle_lookalikes.py` from Unicode {unicodedata.unidata_version} character names; see its docstring. Do not edit by hand.\n")
print("/// Bare angle shapes (brackets, angle quotation marks, chevrons, arrowheads, PRECEDES/SUCCEEDS,\n/// LESS-/GREATER-THAN alone), by code point, and what each becomes inside the fence.\npub(crate) const ANGLE_LOOKALIKES: &[(char, char)] = &[")
for cp, rep, name in rows:
    print(f"    ('\\u{{{cp:04X}}}', '{rep}'), // {name}")
print("];")
