//! The generated module's text: `crates/providers/src/rates/generated.rs`. Deterministic for a
//! given table, laid out as rustfmt would (the module is still declared `#[rustfmt::skip]`, so a
//! rustfmt release can never make the committed file differ from the generator's).

use crate::Result;
use crate::build::{Card, Cost, List, OffPeak, Table, Tr, const_name};
use std::fmt::Write as _;

const WIDTH: usize = 100;

fn tr(t: &Tr) -> Result<String> {
    let h1 = match t.cache_write_1h {
        Some(r) => format!("Some(\"{}\")", r.table_text()?),
        None => "None".to_owned(),
    };
    Ok(format!(
        "tr(\"{}\", \"{}\", \"{}\", \"{}\", {h1})",
        t.input.table_text()?,
        t.output.table_text()?,
        t.cache_read.table_text()?,
        t.cache_write_5m.table_text()?,
    ))
}

fn off_peak(o: &OffPeak, ind: &str) -> Result<String> {
    let peak: Vec<String> = o.peak.iter().map(|(a, b)| format!("({a}, {b})")).collect();
    let holidays: Vec<String> = o.holidays.iter().map(u32::to_string).collect();
    Ok(format!(
        "Some(OffPeak {{\n{ind}    peak: &[{}],\n{ind}    weekdays_only: {},\n{ind}    holidays: &[{}],\n{ind}    covered_from: {},\n{ind}    covered_until: {},\n{ind}    rates: {},\n{ind}}})",
        peak.join(", "),
        o.weekdays_only,
        holidays.join(", "),
        o.covered_from,
        o.covered_until,
        tr(&o.rates)?
    ))
}

/// A card expression. `ind` is the indent of the line the expression starts on; `head` is the
/// text before it on that line (for the one-line width check).
fn card(c: &Card, ind: &str, head: &str, tail: &str) -> Result<String> {
    let mut fields: Vec<String> = Vec::new();
    let inner = format!("{ind}    ");
    for (k, v) in [
        ("long", &c.long),
        ("fast", &c.fast),
        ("fast_long", &c.fast_long),
        ("ultrafast", &c.ultrafast),
        ("ultrafast_long", &c.ultrafast_long),
        ("flex", &c.flex),
        ("flex_long", &c.flex_long),
    ] {
        if let Some(t) = v {
            fields.push(format!("{inner}{k}: Some({}),", tr(t)?));
        }
    }
    if let Some(o) = &c.off_peak {
        fields.push(format!("{inner}off_peak: {},", off_peak(o, &inner)?));
    }
    if let Some((n, inclusive)) = c.long_context {
        fields.push(format!(
            "{inner}long_context: Some(LongContext {{\n{inner}    threshold: {n},\n{inner}    inclusive: {inclusive},\n{inner}}}),"
        ));
    }
    if let Some(g) = c.geo_us {
        fields.push(format!("{inner}geo_us: Some({g}),"));
    }
    if let Some(t) = &c.tools {
        fields.push(format!("{inner}tools: {t},"));
    }
    let base = format!("Card::new({})", tr(&c.standard)?);
    if fields.is_empty() {
        if head.len() + base.len() + tail.len() <= WIDTH {
            return Ok(base);
        }
        return Ok(format!("\n{inner}{base}"));
    }
    Ok(format!(
        "Card {{\n{}\n{inner}..{base}\n{ind}}}",
        fields.join("\n")
    ))
}

pub fn render(t: &Table) -> Result<String> {
    let mut s = String::new();
    s.push_str(
        "// @generated by `mise run rates:sync` (crates/rates-sync) from the snapshots in\n\
         // verify/rates_sources/ and the hand-entered rules in verify/catalog_truth.toml. Do not edit:\n\
         // change a source or a rule and regenerate. `rates_generated_from_sources` fails on any drift.\n\
         \n\
         use super::{CandidateCost, CostCard, OrEndpoint, RowRates, tr};\n\
         use crate::ProviderId;\n\
         use crate::pricing::{Bps, Card, Class, LongContext, OffPeak, Tool};\n",
    );
    let _ = write!(
        s,
        "\n/// OpenRouter's fee on the credits that pay for every request (`[[prose]] openrouter.credit_fee`).\n\
         pub const OPENROUTER_CREDIT_FEE: Bps = {};\n",
        group(t.credit_fee_bps)
    );

    s.push_str("\n// --- per-call fee lists ---\n");
    for (name, fees) in &t.tools {
        let items: Vec<String> = fees
            .iter()
            .map(|(k, f)| format!("(Tool::{k}, {f})"))
            .collect();
        let one = format!("const {name}: &[(Tool, u64)] = &[{}];", items.join(", "));
        if one.len() <= WIDTH {
            let _ = writeln!(s, "{one}");
        } else {
            let _ = writeln!(s, "const {name}: &[(Tool, u64)] = &[");
            for i in &items {
                let _ = writeln!(s, "    {i},");
            }
            s.push_str("];\n");
        }
    }

    s.push_str("\n// --- vendor cards ---\n");
    for (name, c) in &t.cards {
        let head = format!("const {}: Card = ", const_name(name));
        let _ = write!(s, "/// `{name}`.\n{}", head.trim_end());
        let body = card(c, "", &head, ";")?;
        if body.starts_with('\n') {
            let _ = writeln!(s, "{body};\n");
        } else {
            let _ = writeln!(s, " {body};\n");
        }
    }

    s.push_str("// --- OpenRouter endpoints ---\n");
    for (slug, eps) in &t.openrouter {
        let _ = writeln!(
            s,
            "/// `{slug}` (`GET /api/v1/models/{slug}/endpoints`).\nstatic OR_{}: &[OrEndpoint] = &[",
            const_name(slug)
        );
        for e in eps {
            let _ = writeln!(
                s,
                "    OrEndpoint {{\n        host: {:?},\n        tag: {:?},\n        class: Class::{},",
                e.host, e.tag, e.class
            );
            let head = "        card: ";
            let body = card(&e.card, "        ", head, ",")?;
            let _ = writeln!(s, "{head}{body},\n    }},");
        }
        s.push_str("];\n\n");
    }

    s.push_str("pub static ROW_RATES: &[RowRates] = &[\n");
    for r in &t.rows {
        let _ = writeln!(s, "    RowRates {{\n        model: {:?},", r.model);
        match &r.list {
            List::Card(c) => {
                let _ = writeln!(s, "        list: {},", const_name(c));
            }
            List::Inline(tr_) => {
                let _ = writeln!(s, "        list: Card::new({}),", tr(tr_)?);
            }
        }
        s.push_str("        cost: &[\n");
        for (p, c) in &r.cost {
            let card = match c {
                Cost::List => "CostCard::List".to_owned(),
                Cost::Own(name) => format!("CostCard::Own(&{})", const_name(name)),
                Cost::OpenRouter(slug) => format!("CostCard::OpenRouter(OR_{})", const_name(slug)),
                Cost::Unverified(why) => format!("CostCard::Unverified({why:?})"),
            };
            let _ = writeln!(
                s,
                "            CandidateCost {{\n                provider: ProviderId::{p},\n                card: {card},\n            }},"
            );
        }
        s.push_str("        ],\n    },\n");
    }
    s.push_str("];\n");
    Ok(s)
}

/// `10550` → `10_550`.
fn group(n: u128) -> String {
    let d = n.to_string();
    let mut out = String::new();
    for (i, c) in d.chars().enumerate() {
        if i > 0 && (d.len() - i).is_multiple_of(3) {
            out.push('_');
        }
        out.push(c);
    }
    out
}
