//! The snapshot store, `verify/rates_sources/`: one normalized file per source and
//! `manifest.toml`, which records each file's URL, the date its content was fetched, and the
//! sha256 of both the raw response and the snapshot.

use crate::Result;
use crate::sources::SourceDef;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub id: String,
    pub url: String,
    pub file: String,
    /// `YYYY-MM-DD`: when this content was fetched. A re-fetch of identical content keeps it.
    pub fetched: String,
    pub raw_sha256: String,
    pub sha256: String,
}

/// A loaded store: every snapshot's text by source id, each checked against its manifest hash.
pub struct Store {
    pub dir: PathBuf,
    pub entries: BTreeMap<String, Entry>,
    pub text: BTreeMap<String, String>,
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    let d = Sha256::digest(bytes);
    let mut s = String::with_capacity(64);
    for b in d {
        let _ = write!(s, "{b:02x}");
    }
    s
}

pub fn manifest_path(dir: &Path) -> PathBuf {
    dir.join("manifest.toml")
}

pub fn read_manifest(dir: &Path) -> Result<BTreeMap<String, Entry>> {
    let path = manifest_path(dir);
    let text = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
    let t: toml::Table = text
        .parse()
        .map_err(|e| format!("{}: {e}", path.display()))?;
    let mut out = BTreeMap::new();
    for s in t
        .get("source")
        .and_then(toml::Value::as_array)
        .map_or(&[][..], Vec::as_slice)
    {
        let s = s.as_table().ok_or("manifest: [[source]] is not a table")?;
        let get = |k: &str| -> Result<String> {
            s.get(k)
                .and_then(toml::Value::as_str)
                .map(str::to_owned)
                .ok_or_else(|| format!("manifest: a [[source]] lacks `{k}`"))
        };
        let e = Entry {
            id: get("id")?,
            url: get("url")?,
            file: get("file")?,
            fetched: get("fetched")?,
            raw_sha256: get("raw_sha256")?,
            sha256: get("sha256")?,
        };
        out.insert(e.id.clone(), e);
    }
    Ok(out)
}

pub fn write_manifest(dir: &Path, entries: &BTreeMap<String, Entry>) -> Result<()> {
    let mut s = String::from(
        "# @generated by `mise run rates:sync` (crates/rates-sync). Do not edit.\n\
         #\n\
         # One [[source]] per primary pricing source: `file` (under this directory) is the response\n\
         # from `url`, normalized (crates/rates-sync/src/sources.rs). `fetched` is the date this\n\
         # content was first fetched (a re-fetch of identical content keeps it). `raw_sha256` hashes\n\
         # the response as served, `sha256` the snapshot file. `rates_generated_from_sources`\n\
         # checks every `sha256`, then regenerates crates/providers/src/rates/generated.rs from these\n\
         # files and verify/catalog_truth.toml and diffs it.\n",
    );
    for e in entries.values() {
        let _ = write!(
            s,
            "\n[[source]]\nid = {}\nurl = {}\nfile = {}\nfetched = {}\nraw_sha256 = {}\nsha256 = {}\n",
            toml::Value::String(e.id.clone()),
            toml::Value::String(e.url.clone()),
            toml::Value::String(e.file.clone()),
            toml::Value::String(e.fetched.clone()),
            toml::Value::String(e.raw_sha256.clone()),
            toml::Value::String(e.sha256.clone()),
        );
    }
    let path = manifest_path(dir);
    std::fs::write(&path, s).map_err(|e| format!("{}: {e}", path.display()))
}

/// Load every source `defs` names, failing on a missing file, a hash mismatch, or a manifest
/// entry no source defines.
pub fn load(dir: &Path, defs: &[SourceDef]) -> Result<Store> {
    let entries = read_manifest(dir)?;
    let mut text = BTreeMap::new();
    for d in defs {
        let e = entries
            .get(&d.id)
            .ok_or_else(|| format!("{}: no snapshot (run `mise run rates:sync`)", d.id))?;
        if e.url != d.url || e.file != d.file {
            return Err(format!(
                "{}: the manifest's url/file differ from the source's",
                d.id
            ));
        }
        let path = dir.join(&e.file);
        let bytes = std::fs::read(&path).map_err(|err| format!("{}: {err}", path.display()))?;
        let got = sha256_hex(&bytes);
        if got != e.sha256 {
            return Err(format!(
                "{}: sha256 {got} is not the manifest's {} (a snapshot was edited by hand?)",
                e.file, e.sha256
            ));
        }
        let t = String::from_utf8(bytes).map_err(|err| format!("{}: {err}", e.file))?;
        text.insert(d.id.clone(), t);
    }
    let stale: Vec<&String> = entries
        .keys()
        .filter(|k| !defs.iter().any(|d| &d.id == *k))
        .collect();
    if !stale.is_empty() {
        return Err(format!("manifest entries no source defines: {stale:?}"));
    }
    Ok(Store {
        dir: dir.to_owned(),
        entries,
        text,
    })
}

impl Store {
    pub fn get(&self, id: &str) -> Result<&str> {
        self.text
            .get(id)
            .map(String::as_str)
            .ok_or_else(|| format!("no snapshot {id}"))
    }

    /// The snapshot fetched from `url`, for a prose quote's check.
    pub fn by_url(&self, url: &str) -> Option<(&Entry, &str)> {
        self.entries
            .values()
            .find(|e| e.url == url)
            .and_then(|e| self.text.get(&e.id).map(|t| (e, t.as_str())))
    }
}
