//! Generated by `crates/agent/scripts/gen_angle_lookalikes.py` from Unicode 15.0.0 character names; see its docstring. Do not edit by hand.

/// Bare angle shapes (brackets, angle quotation marks, chevrons, arrowheads, PRECEDES/SUCCEEDS,
/// LESS-/GREATER-THAN alone), by code point, and what each becomes inside the fence.
pub(crate) const ANGLE_LOOKALIKES: &[(char, char)] = &[
    ('\u{02C2}', '‹'),  // MODIFIER LETTER LEFT ARROWHEAD
    ('\u{02C3}', '›'),  // MODIFIER LETTER RIGHT ARROWHEAD
    ('\u{02F1}', '‹'),  // MODIFIER LETTER LOW LEFT ARROWHEAD
    ('\u{02F2}', '›'),  // MODIFIER LETTER LOW RIGHT ARROWHEAD
    ('\u{2039}', '‹'),  // SINGLE LEFT-POINTING ANGLE QUOTATION MARK
    ('\u{203A}', '›'),  // SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
    ('\u{226A}', '‹'),  // MUCH LESS-THAN
    ('\u{226B}', '›'),  // MUCH GREATER-THAN
    ('\u{227A}', '‹'),  // PRECEDES
    ('\u{227B}', '›'),  // SUCCEEDS
    ('\u{22D8}', '‹'),  // VERY MUCH LESS-THAN
    ('\u{22D9}', '›'),  // VERY MUCH GREATER-THAN
    ('\u{2329}', '‹'),  // LEFT-POINTING ANGLE BRACKET
    ('\u{232A}', '›'),  // RIGHT-POINTING ANGLE BRACKET
    ('\u{2369}', '›'),  // APL FUNCTIONAL SYMBOL GREATER-THAN DIAERESIS
    ('\u{276C}', '‹'),  // MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
    ('\u{276D}', '›'),  // MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
    ('\u{276E}', '‹'),  // HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
    ('\u{276F}', '›'),  // HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
    ('\u{2770}', '‹'),  // HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT
    ('\u{2771}', '›'),  // HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
    ('\u{27A2}', '›'),  // THREE-D TOP-LIGHTED RIGHTWARDS ARROWHEAD
    ('\u{27A3}', '›'),  // THREE-D BOTTOM-LIGHTED RIGHTWARDS ARROWHEAD
    ('\u{27E8}', '‹'),  // MATHEMATICAL LEFT ANGLE BRACKET
    ('\u{27E9}', '›'),  // MATHEMATICAL RIGHT ANGLE BRACKET
    ('\u{27EA}', '‹'),  // MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
    ('\u{27EB}', '›'),  // MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
    ('\u{29FC}', '‹'),  // LEFT-POINTING CURVED ANGLE BRACKET
    ('\u{29FD}', '›'),  // RIGHT-POINTING CURVED ANGLE BRACKET
    ('\u{2AA1}', '‹'),  // DOUBLE NESTED LESS-THAN
    ('\u{2AA2}', '›'),  // DOUBLE NESTED GREATER-THAN
    ('\u{2ABB}', '‹'),  // DOUBLE PRECEDES
    ('\u{2ABC}', '›'),  // DOUBLE SUCCEEDS
    ('\u{2AF7}', '‹'),  // TRIPLE NESTED LESS-THAN
    ('\u{2AF8}', '›'),  // TRIPLE NESTED GREATER-THAN
    ('\u{2B98}', '‹'),  // THREE-D TOP-LIGHTED LEFTWARDS EQUILATERAL ARROWHEAD
    ('\u{2B9A}', '›'),  // THREE-D TOP-LIGHTED RIGHTWARDS EQUILATERAL ARROWHEAD
    ('\u{3008}', '‹'),  // LEFT ANGLE BRACKET
    ('\u{3009}', '›'),  // RIGHT ANGLE BRACKET
    ('\u{300A}', '‹'),  // LEFT DOUBLE ANGLE BRACKET
    ('\u{300B}', '›'),  // RIGHT DOUBLE ANGLE BRACKET
    ('\u{FE3D}', '‹'),  // PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET
    ('\u{FE3E}', '›'),  // PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET
    ('\u{FE3F}', '‹'),  // PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET
    ('\u{FE40}', '›'),  // PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET
    ('\u{FE64}', '‹'),  // SMALL LESS-THAN SIGN
    ('\u{FE65}', '›'),  // SMALL GREATER-THAN SIGN
    ('\u{FF1C}', '‹'),  // FULLWIDTH LESS-THAN SIGN
    ('\u{FF1E}', '›'),  // FULLWIDTH GREATER-THAN SIGN
    ('\u{1F890}', '‹'), // LEFTWARDS TRIANGLE ARROWHEAD
    ('\u{1F892}', '›'), // RIGHTWARDS TRIANGLE ARROWHEAD
    ('\u{E003C}', '‹'), // TAG LESS-THAN SIGN
    ('\u{E003E}', '›'), // TAG GREATER-THAN SIGN
];
